tenant: "olivinetenantv4"
namespace: "default"
name: "agent-manager-function"
className: "agent_manager.AgentManagerFunction"
py: "/Users/haske107/Desktop/Olivine-V4/agent-manager-function/python-code/agent-manager-function.zip"
inputs:
  - "persistent://olivinetenantv4/default/agent-manager-input"
output: "persistent://olivinetenantv4/default/agent-manager-output"
logTopic: "persistent://olivinetenantv4/default/agent-manager-logs"
autoAck: true
parallelism: 1
resources:
  ram: 1073741824
  cpu: 1.0 